/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BillingInfo {
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'fullName' : string,
  'email' : string,
  'addressLine1' : string,
}
export interface CartItem {
  'size' : Size,
  'productId' : ProductId,
  'quantity' : bigint,
}
export interface CartPublic {
  'owner' : UserId,
  'updatedAt' : Timestamp,
  'items' : Array<CartItem>,
}
export type Collection = { 'Comfort' : null } |
  { 'Atelier' : null } |
  { 'Heritage' : null };
export interface FitQuizResult {
  'completedAt' : Timestamp,
  'confidenceScore' : bigint,
  'recommendedSize' : string,
  'fitPreference' : string,
  'bodyType' : string,
}
export interface FitQuizResultInput {
  'confidenceScore' : bigint,
  'recommendedSize' : string,
  'fitPreference' : string,
  'bodyType' : string,
}
export type OrderId = bigint;
export interface OrderItem {
  'size' : Size,
  'productId' : ProductId,
  'productName' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export interface OrderPublic {
  'id' : OrderId,
  'status' : OrderStatus,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'totalAmount' : bigint,
  'shippingAddress' : ShippingAddress,
  'items' : Array<OrderItem>,
  'billingInfo' : BillingInfo,
}
export type OrderStatus = { 'Delivered' : null } |
  { 'Confirmed' : null } |
  { 'Cancelled' : null } |
  { 'Shipped' : null } |
  { 'Pending' : null };
export type ProductId = bigint;
export interface ProductPublic {
  'id' : ProductId,
  'collection' : Collection,
  'rarityMessage' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'totalStock' : bigint,
  'price' : bigint,
  'sizeStocks' : Array<SizeStock>,
  'material' : string,
  'images' : Array<string>,
}
export interface ShippingAddress {
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'fullName' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : string,
}
export type Size = { 'L' : null } |
  { 'M' : null } |
  { 'S' : null } |
  { 'XL' : null } |
  { 'XS' : null } |
  { 'XXL' : null };
export interface SizeStock { 'size' : Size, 'stock' : bigint }
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserPreferences {
  'vipEnrolledAt' : [] | [Timestamp],
  'vipStatus' : boolean,
  'sizePreference' : [] | [string],
  'newsletter' : boolean,
  'fitQuizResult' : [] | [FitQuizResult],
}
export interface UserProfilePublic {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'preferences' : UserPreferences,
  'updatedAt' : Timestamp,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WishlistItem { 'productId' : ProductId, 'addedAt' : Timestamp }
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addToCart' : ActorMethod<[ProductId, Size, bigint], CartPublic>,
  'addToWishlist' : ActorMethod<[ProductId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createOrder' : ActorMethod<[ShippingAddress, BillingInfo], OrderPublic>,
  'enrollVIP' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], CartPublic>,
  'getFitQuizResult' : ActorMethod<[], [] | [FitQuizResult]>,
  'getOrder' : ActorMethod<[OrderId], [] | [OrderPublic]>,
  'getProduct' : ActorMethod<[ProductId], [] | [ProductPublic]>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfilePublic]>,
  'getVIPStatus' : ActorMethod<[], boolean>,
  'getWishlist' : ActorMethod<[], Array<WishlistItem>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listOrders' : ActorMethod<[], Array<OrderPublic>>,
  'listProducts' : ActorMethod<[], Array<ProductPublic>>,
  'listProductsByCollection' : ActorMethod<[Collection], Array<ProductPublic>>,
  'removeFromCart' : ActorMethod<[ProductId, Size], CartPublic>,
  'removeFromWishlist' : ActorMethod<[ProductId], undefined>,
  'saveCallerUserProfile' : ActorMethod<
    [string, string, UserPreferences],
    UserProfilePublic
  >,
  'saveFitQuizResult' : ActorMethod<[FitQuizResultInput], undefined>,
  'seedProducts' : ActorMethod<
    [
      Array<
        {
          'collection' : Collection,
          'rarityMessage' : string,
          'name' : string,
          'description' : string,
          'price' : bigint,
          'sizeStocks' : Array<SizeStock>,
          'material' : string,
          'images' : Array<string>,
        }
      >,
    ],
    bigint
  >,
  'updateCartQuantity' : ActorMethod<[ProductId, Size, bigint], CartPublic>,
  'updateProductStock' : ActorMethod<[ProductId, Array<SizeStock>], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];