/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const Size = IDL.Variant({
  'L' : IDL.Null,
  'M' : IDL.Null,
  'S' : IDL.Null,
  'XL' : IDL.Null,
  'XS' : IDL.Null,
  'XXL' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const CartItem = IDL.Record({
  'size' : Size,
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const CartPublic = IDL.Record({
  'owner' : UserId,
  'updatedAt' : Timestamp,
  'items' : IDL.Vec(CartItem),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShippingAddress = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'fullName' : IDL.Text,
  'state' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
});
export const BillingInfo = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'addressLine1' : IDL.Text,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Shipped' : IDL.Null,
  'Pending' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'size' : Size,
  'productId' : ProductId,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const OrderPublic = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'totalAmount' : IDL.Nat,
  'shippingAddress' : ShippingAddress,
  'items' : IDL.Vec(OrderItem),
  'billingInfo' : BillingInfo,
});
export const FitQuizResult = IDL.Record({
  'completedAt' : Timestamp,
  'confidenceScore' : IDL.Nat,
  'recommendedSize' : IDL.Text,
  'fitPreference' : IDL.Text,
  'bodyType' : IDL.Text,
});
export const UserPreferences = IDL.Record({
  'vipEnrolledAt' : IDL.Opt(Timestamp),
  'vipStatus' : IDL.Bool,
  'sizePreference' : IDL.Opt(IDL.Text),
  'newsletter' : IDL.Bool,
  'fitQuizResult' : IDL.Opt(FitQuizResult),
});
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'preferences' : UserPreferences,
  'updatedAt' : Timestamp,
});
export const Collection = IDL.Variant({
  'Comfort' : IDL.Null,
  'Atelier' : IDL.Null,
  'Heritage' : IDL.Null,
});
export const SizeStock = IDL.Record({ 'size' : Size, 'stock' : IDL.Nat });
export const ProductPublic = IDL.Record({
  'id' : ProductId,
  'collection' : Collection,
  'rarityMessage' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'totalStock' : IDL.Nat,
  'price' : IDL.Nat,
  'sizeStocks' : IDL.Vec(SizeStock),
  'material' : IDL.Text,
  'images' : IDL.Vec(IDL.Text),
});
export const WishlistItem = IDL.Record({
  'productId' : ProductId,
  'addedAt' : Timestamp,
});
export const FitQuizResultInput = IDL.Record({
  'confidenceScore' : IDL.Nat,
  'recommendedSize' : IDL.Text,
  'fitPreference' : IDL.Text,
  'bodyType' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addToCart' : IDL.Func([ProductId, Size, IDL.Nat], [CartPublic], []),
  'addToWishlist' : IDL.Func([ProductId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createOrder' : IDL.Func([ShippingAddress, BillingInfo], [OrderPublic], []),
  'enrollVIP' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [CartPublic], ['query']),
  'getFitQuizResult' : IDL.Func([], [IDL.Opt(FitQuizResult)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(OrderPublic)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(ProductPublic)], ['query']),
  'getUserProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getVIPStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getWishlist' : IDL.Func([], [IDL.Vec(WishlistItem)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listOrders' : IDL.Func([], [IDL.Vec(OrderPublic)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(ProductPublic)], ['query']),
  'listProductsByCollection' : IDL.Func(
      [Collection],
      [IDL.Vec(ProductPublic)],
      ['query'],
    ),
  'removeFromCart' : IDL.Func([ProductId, Size], [CartPublic], []),
  'removeFromWishlist' : IDL.Func([ProductId], [], []),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, UserPreferences],
      [UserProfilePublic],
      [],
    ),
  'saveFitQuizResult' : IDL.Func([FitQuizResultInput], [], []),
  'seedProducts' : IDL.Func(
      [
        IDL.Vec(
          IDL.Record({
            'collection' : Collection,
            'rarityMessage' : IDL.Text,
            'name' : IDL.Text,
            'description' : IDL.Text,
            'price' : IDL.Nat,
            'sizeStocks' : IDL.Vec(SizeStock),
            'material' : IDL.Text,
            'images' : IDL.Vec(IDL.Text),
          })
        ),
      ],
      [IDL.Nat],
      [],
    ),
  'updateCartQuantity' : IDL.Func([ProductId, Size, IDL.Nat], [CartPublic], []),
  'updateProductStock' : IDL.Func(
      [ProductId, IDL.Vec(SizeStock)],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const Size = IDL.Variant({
    'L' : IDL.Null,
    'M' : IDL.Null,
    'S' : IDL.Null,
    'XL' : IDL.Null,
    'XS' : IDL.Null,
    'XXL' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const CartItem = IDL.Record({
    'size' : Size,
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const CartPublic = IDL.Record({
    'owner' : UserId,
    'updatedAt' : Timestamp,
    'items' : IDL.Vec(CartItem),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShippingAddress = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'fullName' : IDL.Text,
    'state' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
  });
  const BillingInfo = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'addressLine1' : IDL.Text,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Shipped' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'size' : Size,
    'productId' : ProductId,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const OrderPublic = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'owner' : UserId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'totalAmount' : IDL.Nat,
    'shippingAddress' : ShippingAddress,
    'items' : IDL.Vec(OrderItem),
    'billingInfo' : BillingInfo,
  });
  const FitQuizResult = IDL.Record({
    'completedAt' : Timestamp,
    'confidenceScore' : IDL.Nat,
    'recommendedSize' : IDL.Text,
    'fitPreference' : IDL.Text,
    'bodyType' : IDL.Text,
  });
  const UserPreferences = IDL.Record({
    'vipEnrolledAt' : IDL.Opt(Timestamp),
    'vipStatus' : IDL.Bool,
    'sizePreference' : IDL.Opt(IDL.Text),
    'newsletter' : IDL.Bool,
    'fitQuizResult' : IDL.Opt(FitQuizResult),
  });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'preferences' : UserPreferences,
    'updatedAt' : Timestamp,
  });
  const Collection = IDL.Variant({
    'Comfort' : IDL.Null,
    'Atelier' : IDL.Null,
    'Heritage' : IDL.Null,
  });
  const SizeStock = IDL.Record({ 'size' : Size, 'stock' : IDL.Nat });
  const ProductPublic = IDL.Record({
    'id' : ProductId,
    'collection' : Collection,
    'rarityMessage' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'totalStock' : IDL.Nat,
    'price' : IDL.Nat,
    'sizeStocks' : IDL.Vec(SizeStock),
    'material' : IDL.Text,
    'images' : IDL.Vec(IDL.Text),
  });
  const WishlistItem = IDL.Record({
    'productId' : ProductId,
    'addedAt' : Timestamp,
  });
  const FitQuizResultInput = IDL.Record({
    'confidenceScore' : IDL.Nat,
    'recommendedSize' : IDL.Text,
    'fitPreference' : IDL.Text,
    'bodyType' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addToCart' : IDL.Func([ProductId, Size, IDL.Nat], [CartPublic], []),
    'addToWishlist' : IDL.Func([ProductId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createOrder' : IDL.Func([ShippingAddress, BillingInfo], [OrderPublic], []),
    'enrollVIP' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [CartPublic], ['query']),
    'getFitQuizResult' : IDL.Func([], [IDL.Opt(FitQuizResult)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(OrderPublic)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(ProductPublic)], ['query']),
    'getUserProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getVIPStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getWishlist' : IDL.Func([], [IDL.Vec(WishlistItem)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listOrders' : IDL.Func([], [IDL.Vec(OrderPublic)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(ProductPublic)], ['query']),
    'listProductsByCollection' : IDL.Func(
        [Collection],
        [IDL.Vec(ProductPublic)],
        ['query'],
      ),
    'removeFromCart' : IDL.Func([ProductId, Size], [CartPublic], []),
    'removeFromWishlist' : IDL.Func([ProductId], [], []),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, UserPreferences],
        [UserProfilePublic],
        [],
      ),
    'saveFitQuizResult' : IDL.Func([FitQuizResultInput], [], []),
    'seedProducts' : IDL.Func(
        [
          IDL.Vec(
            IDL.Record({
              'collection' : Collection,
              'rarityMessage' : IDL.Text,
              'name' : IDL.Text,
              'description' : IDL.Text,
              'price' : IDL.Nat,
              'sizeStocks' : IDL.Vec(SizeStock),
              'material' : IDL.Text,
              'images' : IDL.Vec(IDL.Text),
            })
          ),
        ],
        [IDL.Nat],
        [],
      ),
    'updateCartQuantity' : IDL.Func(
        [ProductId, Size, IDL.Nat],
        [CartPublic],
        [],
      ),
    'updateProductStock' : IDL.Func(
        [ProductId, IDL.Vec(SizeStock)],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };