/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserPreferences {
    vipEnrolledAt?: Timestamp;
    vipStatus: boolean;
    sizePreference?: string;
    newsletter: boolean;
    fitQuizResult?: FitQuizResult;
}
export type Timestamp = bigint;
export interface ProductPublic {
    id: ProductId;
    collection: Collection;
    rarityMessage: string;
    name: string;
    createdAt: Timestamp;
    description: string;
    totalStock: bigint;
    price: bigint;
    sizeStocks: Array<SizeStock>;
    material: string;
    images: Array<string>;
}
export interface ShippingAddress {
    country: string;
    city: string;
    postalCode: string;
    fullName: string;
    state: string;
    addressLine1: string;
    addressLine2: string;
}
export interface WishlistItem {
    productId: ProductId;
    addedAt: Timestamp;
}
export interface OrderItem {
    size: Size;
    productId: ProductId;
    productName: string;
    quantity: bigint;
    unitPrice: bigint;
}
export interface OrderPublic {
    id: OrderId;
    status: OrderStatus;
    owner: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    totalAmount: bigint;
    shippingAddress: ShippingAddress;
    items: Array<OrderItem>;
    billingInfo: BillingInfo;
}
export interface UserProfilePublic {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    email: string;
    preferences: UserPreferences;
    updatedAt: Timestamp;
}
export interface FitQuizResultInput {
    confidenceScore: bigint;
    recommendedSize: string;
    fitPreference: string;
    bodyType: string;
}
export type UserId = Principal;
export interface BillingInfo {
    country: string;
    city: string;
    postalCode: string;
    fullName: string;
    email: string;
    addressLine1: string;
}
export interface FitQuizResult {
    completedAt: Timestamp;
    confidenceScore: bigint;
    recommendedSize: string;
    fitPreference: string;
    bodyType: string;
}
export type ProductId = bigint;
export interface SizeStock {
    size: Size;
    stock: bigint;
}
export interface CartPublic {
    owner: UserId;
    updatedAt: Timestamp;
    items: Array<CartItem>;
}
export interface CartItem {
    size: Size;
    productId: ProductId;
    quantity: bigint;
}
export type OrderId = bigint;
export enum Collection {
    Comfort = "Comfort",
    Atelier = "Atelier",
    Heritage = "Heritage"
}
export enum OrderStatus {
    Delivered = "Delivered",
    Confirmed = "Confirmed",
    Cancelled = "Cancelled",
    Shipped = "Shipped",
    Pending = "Pending"
}
export enum Size {
    L = "L",
    M = "M",
    S = "S",
    XL = "XL",
    XS = "XS",
    XXL = "XXL"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addToCart(productId: ProductId, size: Size, quantity: bigint): Promise<CartPublic>;
    addToWishlist(productId: ProductId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearCart(): Promise<void>;
    createOrder(shippingAddress: ShippingAddress, billingInfo: BillingInfo): Promise<OrderPublic>;
    enrollVIP(): Promise<void>;
    getCallerUserProfile(): Promise<UserProfilePublic | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCart(): Promise<CartPublic>;
    getFitQuizResult(): Promise<FitQuizResult | null>;
    getOrder(orderId: OrderId): Promise<OrderPublic | null>;
    getProduct(id: ProductId): Promise<ProductPublic | null>;
    getUserProfile(user: UserId): Promise<UserProfilePublic | null>;
    getVIPStatus(): Promise<boolean>;
    getWishlist(): Promise<Array<WishlistItem>>;
    isCallerAdmin(): Promise<boolean>;
    listOrders(): Promise<Array<OrderPublic>>;
    listProducts(): Promise<Array<ProductPublic>>;
    listProductsByCollection(collection: Collection): Promise<Array<ProductPublic>>;
    removeFromCart(productId: ProductId, size: Size): Promise<CartPublic>;
    removeFromWishlist(productId: ProductId): Promise<void>;
    saveCallerUserProfile(name: string, email: string, preferences: UserPreferences): Promise<UserProfilePublic>;
    saveFitQuizResult(result: FitQuizResultInput): Promise<void>;
    seedProducts(entries: Array<{
        collection: Collection;
        rarityMessage: string;
        name: string;
        description: string;
        price: bigint;
        sizeStocks: Array<SizeStock>;
        material: string;
        images: Array<string>;
    }>): Promise<bigint>;
    updateCartQuantity(productId: ProductId, size: Size, quantity: bigint): Promise<CartPublic>;
    updateProductStock(id: ProductId, sizeStocks: Array<SizeStock>): Promise<boolean>;
}
import type { BillingInfo as _BillingInfo, CartItem as _CartItem, CartPublic as _CartPublic, Collection as _Collection, FitQuizResult as _FitQuizResult, OrderId as _OrderId, OrderItem as _OrderItem, OrderPublic as _OrderPublic, OrderStatus as _OrderStatus, ProductId as _ProductId, ProductPublic as _ProductPublic, ShippingAddress as _ShippingAddress, Size as _Size, SizeStock as _SizeStock, Timestamp as _Timestamp, UserId as _UserId, UserPreferences as _UserPreferences, UserProfilePublic as _UserProfilePublic, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addToCart(arg0: ProductId, arg1: Size, arg2: bigint): Promise<CartPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, to_candid_Size_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_CartPublic_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, to_candid_Size_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_CartPublic_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async addToWishlist(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWishlist(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async createOrder(arg0: ShippingAddress, arg1: BillingInfo): Promise<OrderPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1);
                return from_candid_OrderPublic_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1);
            return from_candid_OrderPublic_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async enrollVIP(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enrollVIP();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enrollVIP();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<CartPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return from_candid_CartPublic_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return from_candid_CartPublic_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFitQuizResult(): Promise<FitQuizResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFitQuizResult();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFitQuizResult();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<OrderPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<ProductPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVIPStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getVIPStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVIPStatus();
            return result;
        }
    }
    async getWishlist(): Promise<Array<WishlistItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWishlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWishlist();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listOrders(): Promise<Array<OrderPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrders();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrders();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(): Promise<Array<ProductPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProductsByCollection(arg0: Collection): Promise<Array<ProductPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProductsByCollection(to_candid_Collection_n40(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProductsByCollection(to_candid_Collection_n40(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromCart(arg0: ProductId, arg1: Size): Promise<CartPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0, to_candid_Size_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_CartPublic_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0, to_candid_Size_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_CartPublic_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromWishlist(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWishlist(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string, arg2: UserPreferences): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1, to_candid_UserPreferences_n42(this._uploadFile, this._downloadFile, arg2));
                return from_candid_UserProfilePublic_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1, to_candid_UserPreferences_n42(this._uploadFile, this._downloadFile, arg2));
            return from_candid_UserProfilePublic_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveFitQuizResult(arg0: FitQuizResultInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFitQuizResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFitQuizResult(arg0);
            return result;
        }
    }
    async seedProducts(arg0: Array<{
        collection: Collection;
        rarityMessage: string;
        name: string;
        description: string;
        price: bigint;
        sizeStocks: Array<SizeStock>;
        material: string;
        images: Array<string>;
    }>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.seedProducts(to_candid_vec_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedProducts(to_candid_vec_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCartQuantity(arg0: ProductId, arg1: Size, arg2: bigint): Promise<CartPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCartQuantity(arg0, to_candid_Size_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_CartPublic_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCartQuantity(arg0, to_candid_Size_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_CartPublic_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProductStock(arg0: ProductId, arg1: Array<SizeStock>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProductStock(arg0, to_candid_vec_n46(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProductStock(arg0, to_candid_vec_n46(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CartItem_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CartItem): CartItem {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_CartPublic_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CartPublic): CartPublic {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Collection_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Collection): Collection {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_OrderItem_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderItem): OrderItem {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_OrderPublic_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderPublic): OrderPublic {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ProductPublic_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductPublic): ProductPublic {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_SizeStock_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SizeStock): SizeStock {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Size_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Size): Size {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserPreferences_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPreferences): UserPreferences {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FitQuizResult]): FitQuizResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrderPublic]): OrderPublic | null {
    return value.length === 0 ? null : from_candid_OrderPublic_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProductPublic]): ProductPublic | null {
    return value.length === 0 ? null : from_candid_ProductPublic_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    owner: _UserId;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    totalAmount: bigint;
    shippingAddress: _ShippingAddress;
    items: Array<_OrderItem>;
    billingInfo: _BillingInfo;
}): {
    id: OrderId;
    status: OrderStatus;
    owner: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    totalAmount: bigint;
    shippingAddress: ShippingAddress;
    items: Array<OrderItem>;
    billingInfo: BillingInfo;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n14(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        totalAmount: value.totalAmount,
        shippingAddress: value.shippingAddress,
        items: from_candid_vec_n16(_uploadFile, _downloadFile, value.items),
        billingInfo: value.billingInfo
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    size: _Size;
    productId: _ProductId;
    productName: string;
    quantity: bigint;
    unitPrice: bigint;
}): {
    size: Size;
    productId: ProductId;
    productName: string;
    quantity: bigint;
    unitPrice: bigint;
} {
    return {
        size: from_candid_Size_n8(_uploadFile, _downloadFile, value.size),
        productId: value.productId,
        productName: value.productName,
        quantity: value.quantity,
        unitPrice: value.unitPrice
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    name: string;
    createdAt: _Timestamp;
    email: string;
    preferences: _UserPreferences;
    updatedAt: _Timestamp;
}): {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    email: string;
    preferences: UserPreferences;
    updatedAt: Timestamp;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        preferences: from_candid_UserPreferences_n22(_uploadFile, _downloadFile, value.preferences),
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vipEnrolledAt: [] | [_Timestamp];
    vipStatus: boolean;
    sizePreference: [] | [string];
    newsletter: boolean;
    fitQuizResult: [] | [_FitQuizResult];
}): {
    vipEnrolledAt?: Timestamp;
    vipStatus: boolean;
    sizePreference?: string;
    newsletter: boolean;
    fitQuizResult?: FitQuizResult;
} {
    return {
        vipEnrolledAt: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.vipEnrolledAt)),
        vipStatus: value.vipStatus,
        sizePreference: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.sizePreference)),
        newsletter: value.newsletter,
        fitQuizResult: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.fitQuizResult))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    collection: _Collection;
    rarityMessage: string;
    name: string;
    createdAt: _Timestamp;
    description: string;
    totalStock: bigint;
    price: bigint;
    sizeStocks: Array<_SizeStock>;
    material: string;
    images: Array<string>;
}): {
    id: ProductId;
    collection: Collection;
    rarityMessage: string;
    name: string;
    createdAt: Timestamp;
    description: string;
    totalStock: bigint;
    price: bigint;
    sizeStocks: Array<SizeStock>;
    material: string;
    images: Array<string>;
} {
    return {
        id: value.id,
        collection: from_candid_Collection_n33(_uploadFile, _downloadFile, value.collection),
        rarityMessage: value.rarityMessage,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        totalStock: value.totalStock,
        price: value.price,
        sizeStocks: from_candid_vec_n35(_uploadFile, _downloadFile, value.sizeStocks),
        material: value.material,
        images: value.images
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    size: _Size;
    stock: bigint;
}): {
    size: Size;
    stock: bigint;
} {
    return {
        size: from_candid_Size_n8(_uploadFile, _downloadFile, value.size),
        stock: value.stock
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: _UserId;
    updatedAt: _Timestamp;
    items: Array<_CartItem>;
}): {
    owner: UserId;
    updatedAt: Timestamp;
    items: Array<CartItem>;
} {
    return {
        owner: value.owner,
        updatedAt: value.updatedAt,
        items: from_candid_vec_n5(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    size: _Size;
    productId: _ProductId;
    quantity: bigint;
}): {
    size: Size;
    productId: ProductId;
    quantity: bigint;
} {
    return {
        size: from_candid_Size_n8(_uploadFile, _downloadFile, value.size),
        productId: value.productId,
        quantity: value.quantity
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Delivered: null;
} | {
    Confirmed: null;
} | {
    Cancelled: null;
} | {
    Shipped: null;
} | {
    Pending: null;
}): OrderStatus {
    return "Delivered" in value ? OrderStatus.Delivered : "Confirmed" in value ? OrderStatus.Confirmed : "Cancelled" in value ? OrderStatus.Cancelled : "Shipped" in value ? OrderStatus.Shipped : "Pending" in value ? OrderStatus.Pending : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Comfort: null;
} | {
    Atelier: null;
} | {
    Heritage: null;
}): Collection {
    return "Comfort" in value ? Collection.Comfort : "Atelier" in value ? Collection.Atelier : "Heritage" in value ? Collection.Heritage : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    L: null;
} | {
    M: null;
} | {
    S: null;
} | {
    XL: null;
} | {
    XS: null;
} | {
    XXL: null;
}): Size {
    return "L" in value ? Size.L : "M" in value ? Size.M : "S" in value ? Size.S : "XL" in value ? Size.XL : "XS" in value ? Size.XS : "XXL" in value ? Size.XXL : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderItem>): Array<OrderItem> {
    return value.map((x)=>from_candid_OrderItem_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SizeStock>): Array<SizeStock> {
    return value.map((x)=>from_candid_SizeStock_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderPublic>): Array<OrderPublic> {
    return value.map((x)=>from_candid_OrderPublic_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductPublic>): Array<ProductPublic> {
    return value.map((x)=>from_candid_ProductPublic_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CartItem>): Array<CartItem> {
    return value.map((x)=>from_candid_CartItem_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Collection_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Collection): _Collection {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_SizeStock_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SizeStock): _SizeStock {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_Size_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Size): _Size {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserPreferences_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserPreferences): _UserPreferences {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vipEnrolledAt?: Timestamp;
    vipStatus: boolean;
    sizePreference?: string;
    newsletter: boolean;
    fitQuizResult?: FitQuizResult;
}): {
    vipEnrolledAt: [] | [_Timestamp];
    vipStatus: boolean;
    sizePreference: [] | [string];
    newsletter: boolean;
    fitQuizResult: [] | [_FitQuizResult];
} {
    return {
        vipEnrolledAt: value.vipEnrolledAt ? candid_some(value.vipEnrolledAt) : candid_none(),
        vipStatus: value.vipStatus,
        sizePreference: value.sizePreference ? candid_some(value.sizePreference) : candid_none(),
        newsletter: value.newsletter,
        fitQuizResult: value.fitQuizResult ? candid_some(value.fitQuizResult) : candid_none()
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    collection: Collection;
    rarityMessage: string;
    name: string;
    description: string;
    price: bigint;
    sizeStocks: Array<SizeStock>;
    material: string;
    images: Array<string>;
}): {
    collection: _Collection;
    rarityMessage: string;
    name: string;
    description: string;
    price: bigint;
    sizeStocks: Array<_SizeStock>;
    material: string;
    images: Array<string>;
} {
    return {
        collection: to_candid_Collection_n40(_uploadFile, _downloadFile, value.collection),
        rarityMessage: value.rarityMessage,
        name: value.name,
        description: value.description,
        price: value.price,
        sizeStocks: to_candid_vec_n46(_uploadFile, _downloadFile, value.sizeStocks),
        material: value.material,
        images: value.images
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    size: Size;
    stock: bigint;
}): {
    size: _Size;
    stock: bigint;
} {
    return {
        size: to_candid_Size_n1(_uploadFile, _downloadFile, value.size),
        stock: value.stock
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Size): {
    L: null;
} | {
    M: null;
} | {
    S: null;
} | {
    XL: null;
} | {
    XS: null;
} | {
    XXL: null;
} {
    return value == Size.L ? {
        L: null
    } : value == Size.M ? {
        M: null
    } : value == Size.S ? {
        S: null
    } : value == Size.XL ? {
        XL: null
    } : value == Size.XS ? {
        XS: null
    } : value == Size.XXL ? {
        XXL: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Collection): {
    Comfort: null;
} | {
    Atelier: null;
} | {
    Heritage: null;
} {
    return value == Collection.Comfort ? {
        Comfort: null
    } : value == Collection.Atelier ? {
        Atelier: null
    } : value == Collection.Heritage ? {
        Heritage: null
    } : value;
}
function to_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    collection: Collection;
    rarityMessage: string;
    name: string;
    description: string;
    price: bigint;
    sizeStocks: Array<SizeStock>;
    material: string;
    images: Array<string>;
}>): Array<{
    collection: _Collection;
    rarityMessage: string;
    name: string;
    description: string;
    price: bigint;
    sizeStocks: Array<_SizeStock>;
    material: string;
    images: Array<string>;
}> {
    return value.map((x)=>to_candid_record_n45(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SizeStock>): Array<_SizeStock> {
    return value.map((x)=>to_candid_SizeStock_n47(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
